const CONDITIONS = [
  { name: "Сбалансированный", profile: { fontFamily:"system",fontSize:18,lineHeight:1.55,letterSpacing:0,wordSpacing:0,columnWidth:76,background:"#ffffff",distractionFree:true,readingRuler:false,paragraphFocus:false,enabled:true } },
  { name: "Открытый", profile: { fontFamily:"lexend",fontSize:20,lineHeight:1.85,letterSpacing:.4,wordSpacing:1.5,columnWidth:62,background:"#fffaf0",distractionFree:true,readingRuler:false,paragraphFocus:false,enabled:true } },
  { name: "Фокус", profile: { fontFamily:"system",fontSize:19,lineHeight:1.75,letterSpacing:.15,wordSpacing:1,columnWidth:56,background:"#f2f7f3",distractionFree:true,readingRuler:true,paragraphFocus:true,enabled:true } },
  { name: "Контрастный", profile: { fontFamily:"serif",fontSize:20,lineHeight:1.7,letterSpacing:0,wordSpacing:.5,columnWidth:68,background:"#18221f",distractionFree:true,readingRuler:false,paragraphFocus:false,enabled:true } }
];
const ITEMS = [
  { text:"Городские деревья выполняют больше функций, чем может показаться при беглом взгляде. Их кроны создают тень и уменьшают нагрев асфальта, а листья задерживают часть мелких частиц из воздуха. Корни помогают воде проникать в почву, снижая нагрузку на ливневую канализацию. Однако польза зависит не только от количества деревьев. Важны разнообразие видов, доступ к воде и достаточное пространство для корней. Если высаживать один вид повсюду, единая болезнь может быстро повредить значительную часть городского леса.", q:"Почему разнообразие видов важно?", options:["Оно снижает риск массового повреждения","Оно полностью устраняет загрязнение","Оно ускоряет движение транспорта"], answer:0 },
  { text:"Когда человек вспоминает информацию, память не работает как точная видеозапись. Воспоминание собирается заново из отдельных деталей, знаний и ожиданий. Поэтому попытка воспроизведения может немного менять сам след памяти. Это не означает, что памяти нельзя доверять, но объясняет, почему уверенность человека не всегда гарантирует точность. Исследователи уменьшают такие искажения с помощью нейтральных вопросов и сравнения нескольких независимых источников.", q:"Как исследователи уменьшают искажения памяти?", options:["Задают нейтральные вопросы","Просят отвечать увереннее","Показывают информацию только один раз"], answer:0 },
  { text:"Распределённая практика означает, что обучение разделяется на несколько сессий, между которыми проходит время. При одинаковом общем количестве занятий такой подход часто приводит к более устойчивому запоминанию, чем одна длинная подготовка. Интервалы заставляют мозг восстанавливать материал после частичного забывания. Такое восстановление требует усилий, но именно оно укрепляет доступ к знаниям. Оптимальная длина интервала зависит от того, как долго информацию необходимо сохранять.", q:"Почему интервалы могут помогать запоминанию?", options:["Они требуют повторного восстановления материала","Они полностью предотвращают забывание","Они уменьшают количество изучаемой информации"], answer:0 },
  { text:"Открытые данные позволяют исследователям повторять анализ и проверять выводы друг друга. Однако публикация набора данных не всегда делает исследование полностью воспроизводимым. Необходимы также описание процесса очистки, версии программ, код анализа и объяснение принятых решений. Если в данных присутствует информация о людях, открытость необходимо сочетать с защитой приватности. Иногда безопаснее публиковать агрегированные показатели или синтетические данные.", q:"Чего недостаточно для полной воспроизводимости?", options:["Только публикации исходного набора данных","Описания процесса очистки","Указания версий программ"], answer:0 }
];
let order=[],index=0,started=0,scores=[];
const $=id=>document.getElementById(id);
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function showRound(){const item=ITEMS[index],condition=CONDITIONS[order[index]],p=condition.profile,s=$("sample");$("step").textContent=`Текст ${index+1} из 4`;$("progressBar").style.width=`${(index+1)*25}%`;s.textContent=item.text;s.style.cssText=`font-family:${p.fontFamily==='serif'?'Georgia,serif':p.fontFamily==='lexend'?'Verdana,sans-serif':'system-ui,sans-serif'};font-size:${p.fontSize}px;line-height:${p.lineHeight};letter-spacing:${p.letterSpacing}px;word-spacing:${p.wordSpacing}px;max-width:${p.columnWidth}ch;margin:auto;background:${p.background};color:${p.background==='#18221f'?'#f5f3ed':'#17231d'}`;$("question").textContent=item.q;$("options").innerHTML=item.options.map((o,i)=>`<label><input type="radio" name="answer" value="${i}"> ${o}</label>`).join("");$("comfort").value=3;$("comfortOut").textContent="3 / 5";$("error").textContent="";started=Date.now();}
$("begin").onclick=()=>{order=shuffle([0,1,2,3]);$("intro").classList.add("hidden");$("round").classList.remove("hidden");showRound()};
$("comfort").oninput=()=>$("comfortOut").textContent=`${$("comfort").value} / 5`;
$("next").onclick=()=>{const selected=document.querySelector('input[name="answer"]:checked');if(!selected){$("error").textContent="Выберите ответ";return}const seconds=Math.max(5,(Date.now()-started)/1000),correct=+selected.value===ITEMS[index].answer?1:0,comfort=+$("comfort").value;scores.push({condition:order[index],seconds,correct,comfort});index++;if(index<4)return showRound();finish()};
function finish(){const fastest=Math.min(...scores.map(x=>x.seconds));scores.forEach(x=>x.total=x.correct*.65+(fastest/x.seconds)*.15+(x.comfort/5)*.20);const winner=scores.sort((a,b)=>b.total-a.total)[0],condition=CONDITIONS[winner.condition];window.calibratedProfile=condition.profile;$("round").classList.add("hidden");$("complete").classList.remove("hidden");$("resultTitle").textContent=`Подходит профиль «${condition.name}»`;$("resultText").textContent=`Он дал лучший баланс понимания, времени и субъективного комфорта. Понимание имело наибольший вес.`;$("chosen").innerHTML=`<span>Размер: <b>${condition.profile.fontSize}px</b></span><span>Строка: <b>${condition.profile.lineHeight}×</b></span><span>Ширина: <b>${condition.profile.columnWidth} зн.</b></span>`}
$("useProfile").onclick=async()=>{const stored=await chrome.storage.local.get("calibrationHistory");await chrome.storage.local.set({profile:window.calibratedProfile,calibrationHistory:[...(stored.calibrationHistory||[]),{createdAt:Date.now(),scores,profile:window.calibratedProfile}]});$("useProfile").textContent="Профиль сохранён";$("useProfile").disabled=true};
